package com.example.conrep.ui.report;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;

import com.example.conrep.R;
import com.example.conrep.database.report.ReportEntity;
import com.example.conrep.database.site.ConstructionSiteEntity;
import com.example.conrep.ui.BaseActivity;
import com.example.conrep.ui.site.ViewConstructionSite;
import com.example.conrep.ui.viewmodel.constructionSite.ConstructionSiteViewModel;
import com.example.conrep.ui.viewmodel.report.ReportViewModel;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class FileReport extends BaseActivity {

    private int siteID;

    private Button fileReportBtn;

    private ReportEntity report;
    private ReportViewModel viewModel;

    private EditText etReportName;
    private EditText etReportHours;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getLayoutInflater().inflate(R.layout.activity_add_construction_site, frameLayout);

        siteID = getIntent().getIntExtra("siteID", 1);

        initiateView();

    }

    private void initiateView() {
        etReportName = findViewById(R.id.etReportName);
        etReportHours = findViewById(R.id.etReportHours);

        fileReportBtn = findViewById(R.id.btnFileReport);
        fileReportBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                addSite();
            }
        });
    }

    private void addSite() {
        boolean testBool = false;
        if(etReportName.getText().toString() == null){
            etReportName.setError(getString(R.string.error_empty_field));
            testBool = true;
        }
        if (etReportHours.getText().toString() == null){
            etReportHours.setError(getString(R.string.error_empty_field));
            testBool = true;
        }
        if(testBool){
            return;
        }
        report = new ReportEntity();
        report.setWorkerName(etReportName.getText().toString());
        report.setHours(Integer.parseInt(etReportHours.getText().toString()));
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime now = LocalDateTime.now();
        report.setDate(now.toString());
        report.setSiteReport(siteID);


        // todo call insert function for construction site

        Intent intent = new Intent(this, ViewConstructionSite.class);
        intent.putExtra("siteID", 0);// todo 0 has to be replaced with whatever ID will be generated by the DB
        startActivity(intent);
    }
}